### ISSUE TITLE
Runnable jar?

### ISSUE THREAD

**Issue by jakebeal** [Protelis/Protelis-Demo#1]
Should we include an ability to produce a single executable jar that you can include and run a hello world out of, where you can just grab that and run it.  Possible workflows to support: 
- fat Jar, pop in a project and run
- fat Jar, run a Hello World demo directly

**Comment by DanySK** [comment]
Hi @jakebeal, in the current project configuration, we could produce 6 runnable jars. Do you think they are still useful?

**Comment by jakebeal** [comment]
I think that this would, in fact, still be useful.  One of the barriers to using Protelis is wrangling a build up and running, and this would help to mitigate that.

**Comment by DanySK** [comment]
I found some time to refresh this project and improve the automatic maintenance. If I configured everything correctly (which I doubt), the fatJars should appear on the next release.

**Comment by DanySK** [comment]
Against all odds, it worked at first attempt. Fat jars and now, and will for every update, released on GitHub under "Releases".
Closing as completed, please reopen if more is needed.
